version: 'version'
services:
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGREST_DB: julian
  volumes:
    - ./pgdata:/var/lib/postgresql/
  ports:
    -"5432:5432"
web:
  image: express_tutorial
  depends_on: 
    - db
  ports:
    - "4000:4000"